### PR TITLE
Add a sprite for spikeball traps.

### PR DESCRIPTION
**Pull request by jaythebusinessgoose**
This sprite takes up the two tiles that spikeballs will take up in-game so it is easier to tell what space they will occupy.

### CODE REVIEW

**Comment by jaythebusinessgoose** [comment]
This one is also defined in the ItemSheet, but I am unsure if that one is used in any context outside of the level editor, so I feel uncomfortable with removing it unless someone can confirm that it is okay to do so.

**Comment by gmjosack** [comment]
merge conflict :laughing: doing too many in parallel. heh

**Comment by jaythebusinessgoose** [comment]
> merge conflict 😆 doing too many in parallel. heh

Yeah, I was prepared for that. 😩 I wasn't sure if git would like PRs from two branches in sequence so I did them in parallel instead.

**Comment by gmjosack** [comment]
Feel free to bundle them in one PR if you've got a list you're working through.

**Pull request merged**
