### PR TITLE
Allow curing status effects via ankh

### PR DESCRIPTION
**Pull request by mauvealerts**
[per Hectique](https://discord.com/channels/150366712775180288/758716867572531220/864842434026537031) in s2-rule-discussion

### CODE REVIEW

**Comment by mauvealerts** [comment]
Maybe we should set `cured_status` in this case? Since it's never read, I'm assuming it should align with `is_low_percent`

**Comment by gmjosack** [comment]
Wouldn't this still fail after you're revived since you'd have the self.cursed/poisened set to True but no longer have those status effects? Maybe if you're dying it would set self.poison/cursed back to False

**Comment by mauvealerts** [comment]
We still update self.cursed/poisoned further down. This change allows the transition without invalidating chain low% ([demo video](https://youtu.be/m3yDsx9UskI)).

Death% during the revive animation is happens on main branch too, but afterwards it's Chain Sunken City% (i.e. low% is lost)

**Comment by gmjosack** [comment]
Ah I missed the context below on the diff. Thanks!

**Pull request merged**
