### PR TITLE
Installs via WebSocket in Rust, wire mods to Tauri, report progress

### PR DESCRIPTION
**Pull request by mauvealerts**
Leaving this as a draft since there's a tiny bit more work to actually connect install commands to, well, install the mod.

I think some version the `backoff` wrapper is probably worth pulling into a separate Cargo package, along with the `tower`+`hyper` HTTP client (from previous work). I expect they'll be handy for, e.g. polling GitHub for releases.

A bit more about `backoff`: the `Future` adapter included in the crate has a couple minor downsides. Understandably, it doesn't support cancellation AFAICT (just deadlines), and it doesn't integrate with `tokio`'s clock (e.g. to advance time in tests). I also found creating a custom `Error` type more ergonomic than the `backoff` version, which is oriented towards HTTP requests; it was awkward in the context of long-lived WebSocket connection that never "completes successfully."

### CODE REVIEW

**Comment by mauvealerts** [comment]
I made `ml2_net` and shoved into this PR. I think the control flow is more legible now

**Comment by mauvealerts** [comment]
Before I forget … there are a  some behavior details I want to highlight
1) Status codes that get retried. I went with just 429, 503, 504 (rate limit, load, gateway timeout). I'm on the fence about 500 and 502.
3) Backoff parameters. Defaults are min 0.5s, max 60s, multiplier 1.5, randomization of 0.5. So, it starts with [0.25, 0.75] and on 12th attempt reaches the max of [30, 90] seconds
4) (way less important IMO) I configured ping for every 15-25s lagerly based on `websockets` python  interval of 20s. It waits for a pong (timeout 10s) before starting the timer for the next ping.

**Comment by mauvealerts** [comment]
This now includes:
* Wiring all functionality to Tauri commands+events
* Reporting download progress

**Comment by mauvealerts** [comment]
Added logos via custom URI scheme. Due to WebView2's quirkiness, it's exposed strangely ... to load the logo for `fyi.tele-trainer` use webview URL `https://mod-logo.localhost/fyi.tele-trainer`

**Review by gmjosack — APPROVED** [review]

**Pull request merged**
